/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_forsafe_facamera_Facamera */

#ifndef _Included_Audio_Interface
#define _Included_Audio_Interface

#define JNI_API_NAME(A)		Java_com_great_happyness_Codec_CodecMedia##A

#ifdef __cplusplus
extern "C"
{
#endif




#ifdef __cplusplus
}
#endif

#endif
